# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sub-MustEval
version:      0.01
version_from: 
installdirs:  site
requires:
    Attribute::Handlers:           0.78
    Carp:                          0
    strict:                        0
    Symbol:                        0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
